CREATE DATABASE TestDb;
GO
CREATE SCHEMA TestSchema;
GO
CREATE TABLE TestSchema.TestTable
(ID INT NOT NULL,
 Name VARCHAR(20),
 IsSold BIT,
 InvoiceDate DATE);
GO

USE TestDb
GO
INSERT INTO TestSchema.TestTable
VALUES
(1, 'Boat', 1, '2020-11-08'),
(2,'Auto', 0, '2020-11-09'),
(3,'Plane', null, '2020-12-09')
GO

CREATE USER TestUser WITH PASSWORD='Cheb0ks@ry'
GO
GRANT CONNECT TO TestUser	
GO
GRANT SELECT ON TestTable TO TestUser 
GO
SELECT CURRENT_USER
GO
DROP USER TestUser